#!/bin/bash
#SBATCH -N 5 --ntasks-per-node 128
#SBATCH -t 00:10:00
#SBATCH -p RM
#SBATCH -J 'RM'


module load gcc
module load cuda/11.1.1
module load openmpi/3.1.6-gcc8.3.1
PATH=$PATH:/jet/home/schwinns/pkgs/gromacs/2020.5
source /jet/home/schwinns/pkgs/gromacs/2020.5/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups

mpirun -np 640 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  N5_np640.log  -ntomp 1


             






