#!/bin/bash
#SBATCH -N 1 --ntasks-per-node 5
#SBATCH -t 00:20:00
#SBATCH -p GPU-small --gres=gpu:1
#SBATCH -J 'G1'

module load gcc
module load cuda/11.1.1
module load openmpi/3.1.6-gcc8.3.1
PATH=$PATH:/jet/home/schwinns/pkgs/gromacs/2020.5
source /jet/home/schwinns/pkgs/gromacs/2020.5/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups


mpirun -np 1 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G1_np1_nomp4.log  -ntomp 4
mpirun -np 2 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G1_np2_nomp2.log  -ntomp 2
mpirun -np 4 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G1_np4_nomp1.log  -ntomp 1
mpirun -np 5 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G1_np5_nomp1.log  -ntomp 1
