#!/bin/bash
#SBATCH -N 1 --ntasks-per-node 1
#SBATCH -t 00:01:00
#SBATCH -p RM-shared
#SBATCH -J 'grompp'

module load gcc
module load cuda/11.1.1
module load openmpi/3.1.6-gcc8.3.1
PATH=$PATH:/jet/home/schwinns/pkgs/gromacs/2020.5
source /jet/home/schwinns/pkgs/gromacs/2020.5/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups
mpirun -np 1 gmx_mpi grompp -f ../npt.mdp -p ../topol.top -c ../nvt.gro -o npt -maxwarn 1
             






