#!/bin/bash
#SBATCH -N 1 --ntasks-per-node 40
#SBATCH -t 00:20:00
#SBATCH -p GPU-small --gres=gpu:8
#SBATCH -J 'G8'

module load gcc
module load cuda/11.1.1
module load openmpi/3.1.6-gcc8.3.1
PATH=$PATH:/jet/home/schwinns/pkgs/gromacs/2020.5
source /jet/home/schwinns/pkgs/gromacs/2020.5/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups


mpirun -np 8 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G8_np8_nomp4.log  -ntomp 4
mpirun -np 16 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G8_np16_nomp2.log  -ntomp 2
mpirun -np 32 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G8_np32_nomp1.log  -ntomp 1
mpirun -np 40 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G8_np40_nomp1.log  -ntomp 1

