#!/bin/bash
#SBATCH -N 1 --ntasks-per-node 20
#SBATCH -t 04:00:00
#SBATCH -p GPU-small --gres=gpu:4
#SBATCH -J 'G4'

module load gcc
module load cuda/11.1.1
module load openmpi/3.1.6-gcc8.3.1
PATH=$PATH:/jet/home/schwinns/pkgs/gromacs/2020.5
source /jet/home/schwinns/pkgs/gromacs/2020.5/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups


#mpirun -np 4 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G4_np4_nomp4.log  -ntomp 4
mpirun -np 8 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G4_np8_nomp2.log  -ntomp 2
mpirun -np 16 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G4_np16_nomp1.log  -ntomp 1
mpirun -np 20 gmx_mpi mdrun -v -s ../npt.tpr -o npt -g  G4_np20_nomp1.log  -ntomp 1

